FROM node:20-alpine AS build
WORKDIR /app
COPY . .
RUN corepack enable && pnpm install --frozen-lockfile
RUN pnpm --filter shared build && pnpm --filter web build

FROM nginx:1.27-alpine
WORKDIR /usr/share/nginx/html
COPY docker/nginx.web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/src/apps/web/dist ./
CMD ["nginx", "-g", "daemon off;"]
